CREATE TABLE day_meal
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id    BIGINT REFERENCES person (id),
    product_id   BIGINT REFERENCES product (id),
    weight       INT,
    date         TIMESTAMP,
    is_breakfast boolean,
    is_dinner    boolean,
    is_supper    boolean
);

INSERT INTO day_meal(person_id, product_id, weight)
VALUES (1, 1, 300),
       (1, 2, 500),
       (1, 3, 200),
       (2, 2, 2500)
