version: '3.8'
services:
  db-fcc:
    container_name: db-fcc
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - '5432:5432'

  backend:
    build:
      context: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-fcc:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
    depends_on:
      - db-fcc

  front:
    build:
      dockerfile: Dockerfile
      context: front
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./front:/app
    stdin_open: true
    tty: true